const SERVO_ID = {
    LEFT: 'l',
    RIGHT: 'r',
    LIFTER: 'i'
};

const SERVO_POSITION = {
    DOWN: 102,
    UP: 90
};

const ARM_LENGTH_MM = 50;
const CANVAS_SCALE_FACTOR = 4;
const ARM_LENGTH = ARM_LENGTH_MM * CANVAS_SCALE_FACTOR;
const SEGMENT_LENGTH = ARM_LENGTH / 4;
const DIGIT_OFFSET = SEGMENT_LENGTH * 1.5;
const FIRST_CHAR_X = -2 * DIGIT_OFFSET;
// const SKEW_FACTOR = 0.05;

module.exports = {
    SERVO_ID: SERVO_ID,
    SERVO_POSITION: SERVO_POSITION,
    CANVAS_SCALE_FACTOR: CANVAS_SCALE_FACTOR,
    ARM_LENGTH: ARM_LENGTH,
    DIGIT_OFFSET: DIGIT_OFFSET,
    FIRST_CHAR_X: FIRST_CHAR_X
};